name: PR Build
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
env:
  GOTOOLCHAIN: local
jobs:
  lint-linux:
    strategy:
      matrix:
        go-version:
          - setup: "1.21"
            makeArgs: ""
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: v2/go.sum
          go-version: ${{ matrix.go-version.setup }}
      - name: Lint
        run: make lint ${{ matrix.go-version.makeArgs }}

  test-linux:
    strategy:
      matrix:
        go-version:
          - setup: "1.21"
            makeArgs: ""
          - setup: "1.23.0-rc.2"
            makeArgs: "go_version_full=1.23rc2"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: v2/go.sum
          go-version: ${{ matrix.go-version.setup }}
      - name: Test
        run: make test ${{ matrix.go-version.makeArgs }}

  lint-windows:
    strategy:
      matrix:
        go-version:
          - setup: "1.21"
            makeArgs: ""
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: v2/go.sum
          go-version: ${{ matrix.go-version.setup }}
      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            base-devel 
            mingw-w64-x86_64-toolchain 
            unzip 
      - name: Lint
        run: make lint ${{ matrix.go-version.makeArgs }}

  test-windows:
    strategy:
      matrix:
        go-version:
          - setup: "1.21"
            makeArgs: ""
          - setup: "1.23.0-rc.2"
            makeArgs: "go_version_full=1.23rc2"
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: v2/go.sum
          go-version: ${{ matrix.go-version.setup }}
      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            base-devel 
            mingw-w64-x86_64-toolchain 
            unzip 
      - name: Test
        run: make test ${{ matrix.go-version.makeArgs }}

  # This job is just here to make sure that the other jobs have completed
  # and is used as a single job to block PR merge from. GH doesn't have a
  # way to say "all jobs from this action", which would be ideal.
  success:
    needs: [lint-linux, test-linux, lint-windows, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Shout it out
        run: echo SUCCESS

